# -*- coding: utf-8 -*-
"""Day-07_Mini_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fIZ2SVh0dBsKGii_Ofd52AtpnnNywKKp
"""

!pip install sentence-transformers chromadb

from sentence_transformers import SentenceTransformer
import chromadb
model = SentenceTransformer('all-MiniLM-L6-v2')
notes = [
    "Machine Learning trains computers using data.",
    "Python is a popular programming language.",
    "Cloud Computing provides resources over the internet.",
    "Data Engineering builds data pipelines.",
    "Artificial Intelligence enables machines to think."
]

client = chromadb.Client()
collection = client.get_or_create_collection("college_notes")
print("Collection Created!")

embeddings = model.encode(notes).tolist()
collection.add(
    documents=notes,
    embeddings=embeddings,
    ids=["1","2","3","4","5"]
)

print("Total Documents:",
collection.count())
query = "How do machines learn from data?"
query_embedding = model.encode(query).tolist()
results = collection.query(
    query_embeddings=[query_embedding],
    n_results=2)
print(results["documents"])

collection.add(
    documents=[
        "Neural networks are used in deep learning."
    ],
    embeddings=model.encode(
        ["Neural networks are used in deep learning."]
    ).tolist(),
    ids=["6"],
    metadatas=[
        {"subject":"AI"}
    ]
)

results = collection.query(
    query_embeddings=[
        model.encode(
            "deep learning"
        ).tolist()
    ],
    where={
        "subject":"AI"
    }
)
print(results["documents"])
query = "machine"

for note in notes:
    if query.lower() in note.lower():
        print(note)

query = "computers learning from data"
query_embedding = model.encode(
    query
).tolist()
results = collection.query(
    query_embeddings=[query_embedding],
    n_results=2
)
print(results["documents"])