# -*- coding: utf-8 -*-
"""Day_04_PySpark.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12Xu6spEgDcADkIAuww53-0uO8GeKeR6u
"""

import joblib

a=joblib.load('Linear.pkl')

a.predict([[100]])

!pip install pyspark -quiet

from pyspark.sql import SparkSession
from pyspark.sql import functions
from pyspark.sql.functions import year, month,to_date,col,round as spark_round
import matplotlib.pyplot as plt
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

spark=SparkSession.builder \
.appName('Day4_BigData_Sales') \
.config('spark.sql.adaptive.enabled','true')\
.getOrCreate()

print("Spark Version:",spark.version)
print("SparkSession:ACTIVE")
print("Application:",spark.sparkContext.appName)

#select specific columns
#df.select("column_name","column_name").show(5)
#Filter rows
#df.filter(F.col("column_name")>value (50000)).show()

df_bronze = spark.read \
     .option('header', 'true')\
     .option('inferSchema', 'true')\
      .csv('large_sales_data.csv')

print('===Bronze Layer-Raw Data ===')
print(f'Rows:{df_bronze.count()}')
print(f'columns:{len(df_bronze.columns)}')
print(f'Names:{df_bronze}')
print()
df_bronze.printSchema()

print("First five rows:")
df_bronze.show(5,truncate=False)
print("\nBasic statistics for numeric columns:")
df_bronze.select('quantity','unit_price','revenue').describe().show()

import os

# Function to get directory/file size
def get_dir_size(path='.'):
    total = 0
    if os.path.isfile(path):
        total = os.path.getsize(path)
    elif os.path.isdir(path):
        for entry in os.listdir(path):
            full_path = os.path.join(path, entry)
            if os.path.isfile(full_path):
                total += os.path.getsize(full_path)
            elif os.path.isdir(full_path):
                total += get_dir_size(full_path) # Recursively sum up directory sizes
    return total / 1024 # return size in KB

#save bronze layer as parquet
df_bronze.write.mode('overwrite').parquet('sales_bronze.parquet')
print("Bronze parquet saved:sales_bronze-parquet")

df_silver=df_bronze.dropDuplicates().dropna(subset=['order_id','product','revenue'])
df_silver=df_silver.withColumn('order_date',to_date(col('order_date'),'YYYY-MM-DD'))
df_silver=df_silver.withColumn('order_year',year(col('order_date'))).withColumn('order_month',month(col('order_date')))
df_silver=df_silver.withColumn('revenue_category',functions.when(col('revenue')>40000,'High')\
.when(col('revenue')>10000,'Meduim').otherwise('Low'))
print("Silver layer rows:",df_silver.count())
print("New columns added:order_year,order_month,revenue_category")
df_silver.select('product','revenue','order_year','order_month','revenue_category').show(7)

df_silver.write.mode('overwrite').parquet('sales_silver.parquet')
print("Silver parquet saved successfully")
print(f"Silver size:{get_dir_size('sales_silver.parquet'):.1f} KB")
df_verify=spark.read.parquet('sales_silver.parquet')
df_verify.show(5)

top_products=df_silver.groupBy('product').agg(functions.sum('revenue').alias('total_revenue'),
functions.count('order_id').alias('num_orders'),functions.avg('order_id').alias('avg_order_revenue'))\
.orderBy('total_revenue',ascending=False).limit(5)

print("===Top 5 products by revenue===:")
top_products.show(truncate=False)

region_revenue=df_silver.groupBy('region').agg(functions.sum('revenue').alias('total_revenue'),
functions.count('order_id').alias('total_orders'),functions.countDistinct('customer_name').alias('unique_customers'))\
.orderBy('total_revenue',ascending=False)

print("===Revenue by region===")
region_revenue.show(truncate=False)

gold_region=region_revenue
gold_region.write.mode('overwrite').parquet("gold_region_revenue.parquet")
print("Gold 1 saved: gold_region_revenue.parquet ")

gold_products=df_silver.groupBy('product','category').agg(functions.sum('revenue').alias('total_revenue'),
functions.count('order_id').alias('unit_sold'),
spark_round(functions.avg('quantity').alias('avg_quantity_per_order')),
functions.max('revenue').alias('largest_revenue'))\
.orderBy('total_revenue',ascending=False)

# print("===Product Summary===")
gold_products.write.mode('overwrite').parquet("gold_product_summary.parquet")
print("Gold 2 saved: gold_product_summary.parquet ")

monthly_trend=df_silver.groupBy('order_month').agg(functions.sum('revenue').alias('monthly_revenue'),
functions.count('order_id').alias('monthly_orders')).orderBy('order_month')
print("===Monthly revenue trend===")
monthly_trend.show(12)

gold_monthly_trend=monthly_trend
gold_monthly_trend.write.mode('overwrite').parquet("gold_monthly_trend.parquet")
print("Gold 3 saved: gold_monthly_trend.parquet ")

region_pd=spark.read.parquet('gold_region_revenue.parquet').toPandas()
product_pd=spark.read.parquet('gold_product_summary.parquet').toPandas()
monthly_pd=spark.read.parquet('gold_monthly_trend.parquet').toPandas()

print("Gold tables converted to pandas:")
print("Region:",region_pd.shape)
print("Products:",product_pd.shape)
print("Monthly:",monthly_pd.shape)

region_pd=region_pd.sort_values(by='total_revenue',ascending=False)
product_pd=product_pd.sort_values(by='total_revenue',ascending=False)
monthly_pd=monthly_pd.sort_values(by='order_month')



#Build the Big Sales Dashboard
import matplotlib.pyplot as plt
fig,axes=plt.subplots(2,2,figsize=(18,13))
fig.suptitle("Big Sales Dashboard -Pyspark Mediallian pipeline\n"
                        '5,000 orders | Processed with Apache Spark',
                         fontsize=18,fontweight='bold',y=1.01)
colors4=['#23CD6F','#DD6B7F','#FEB5DA','#094782']

ax1=axes[0][0]
bars1=ax1.bar(region_pd['region'],region_pd['total_revenue'],
                color=colors4[:len(region_pd)],edgecolor='black')

for bars in bars1:
    ax1.text(bars.get_x()+bars.get_width()/2,bars.get_height()*1.01,
                      f'${bars.get_height()/1e6:.1f}M',
                     ha='center',fontweight='bold',fontsize=12,color='#1E2761')
    ax1.set_title("Total revenue by region",fontsize=14,fontweight='bold')
    ax1.set_ylabel("Revenue:($)")
    ax1.set_xlabel("Regions")
    ax1.yaxis.set_major_formatter(plt.FuncFormatter(lambda x,_y:f'{x/1e6:.1f}M'))
    ax1.grid(axis='y',alpha=0.3,linestyle='--')


    ax2=axes[0][1]
    top5_prod=product_pd.head(5).sort_values('total_revenue')
    bars2=ax2.barh(top5_prod['product'],top5_prod['total_revenue'],
                    color='#12239E',edgecolor='white')
    for bars in bars2:
        ax2.text(bars.get_width()*1.01,bars.get_y()+bars.get_height()/2,
                        f'${bars.get_width()/1e6:.1f}M',
                        va='center',fontweight='bold',fontsize=9,color='#1E2761')
    ax2.set_title("Top 5 products by revenue ",fontsize=14,fontweight='bold')
    ax2.set_xlabel("Total Revenue:($)")
    ax2.xaxis.set_major_formatter(plt.FuncFormatter(lambda x,_y:f'{x/1e6:.1f}M'))
    ax2.grid(axis='x',alpha=0.3,linestyle='--')

#

print("===Activity 2: File Format Comparison===")
print()

csv_kb=get_dir_size('large_sales_data.csv')
bronnze_kb=get_dir_size('sales_bronze.parquet')
silver_kb=get_dir_size('sales_silver.parquet')
gold_kb=get_dir_size('gold_region_revenue.parquet')
get_dir_size('gold_product_summary.parquet')
get_dir_size('gold_monthly_trend.parquet')
print(f"CSV file size:{csv_kb:.1f} KB")